title       = "zhaopin"
baseURL     = "https://zhaopin-cli.tamnd.com/"
description = "Zhaopin job search CLI"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/zhaopin-cli"
